//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LucaMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RistoranteEntities : DbContext
    {
        public RistoranteEntities()
            : base("name=RistoranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contorno> Contorno { get; set; }
        public virtual DbSet<Dolce> Dolce { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Primo> Primo { get; set; }
        public virtual DbSet<Secondo> Secondo { get; set; }
    }
}
