//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LucaMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int id { get; set; }
        public System.DateTime dataMenu { get; set; }
        public string tipoMenu { get; set; }
        public Nullable<int> primo { get; set; }
        public Nullable<int> secondo { get; set; }
        public Nullable<int> contorno { get; set; }
        public Nullable<int> dolce { get; set; }
    
        public virtual Contorno Contorno1 { get; set; }
        public virtual Dolce Dolce1 { get; set; }
        public virtual Primo Primo1 { get; set; }
        public virtual Secondo Secondo1 { get; set; }
    }
}
